# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BatchProjectRasters.py
# Created on: 2016-09-08 10:57:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Output_Coordinate_System = "PROJCS['WGS_1984_UTM_zone_33S',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['false_easting',500000.0],PARAMETER['false_northing',10000000.0],PARAMETER['central_meridian',15.0],PARAMETER['scale_factor',0.9996],PARAMETER['latitude_of_origin',0.0],UNIT['Meter',1.0]]"
Downloads = "C:\\Users\\jymutua\\Downloads"
Hansen_GFC2015_treecover2000_10S_010E_tif = "C:\\Users\\jymutua\\Downloads\\Hansen_GFC2015_treecover2000_20S_020E.tif"
v_Name_ = "D:\\Trash\\%Name%"

# Process: Iterate Rasters
arcpy.IterateRasters_mb(Downloads, "", "TIF", "NOT_RECURSIVE")

# Process: Project Raster
arcpy.ProjectRaster_management(Hansen_GFC2015_treecover2000_10S_010E_tif, v_Name_, Output_Coordinate_System, "NEAREST", "28.6824804653631 28.6824804653631", "", "", "")

