# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BatchExtractMultiValues.py
# Created on: 2016-03-09 14:20:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Wote_point_09032016 = "Wote_point_09032016"
af_ALUM3S_T__M_xd1_250m_tif = "Z:\\CIAT GIS DATASETS\\Regional Level\\Africa\\ISRIC_250m\\af_ALUM3S_T__M_xd1_250m.tif"

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(Wote_point_09032016, "'Z:\\CIAT GIS DATASETS\\Regional Level\\Africa\\ISRIC_250m\\af_ALUM3S_T__M_xd1_250m.tif' af_ALUM3S_", "NONE")

